on:
  workflow_call:
    inputs:
      os:
        default: ubuntu-latest
        required: false
        type: string
jobs:
  setup:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/setup-node@main
      - uses: actions/setup-go@main
      - uses: docker-practice/actions-setup-docker@master
      - run: curl https://raw.githubusercontent.com/davidkhala/oracle-linux-utils/main/7/git.sh | bash -s update
        name: setup git
      - run: sudo yum groupinstall -y "Development Tools" "Development Libraries"
        name: setup build essential
      
        
      
