name: actions-syntax-test

# Controls when the action will run. 
on: workflow_dispatch
jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@master
