name: actions-syntax-test

# Controls when the action will run. 
on: 
  workflow_dispatch:
  push:
    tags:
    - v*
jobs:
  ServiceNow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ServiceNow CI/CD Instance Scan
        uses: ServiceNow/sncicd-instance-scan@2.0.0
        with:
          scantype: full # point, suite_combo, suite_scoped, suite_update
        env:
          nowUsername: Admin
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowScanInstance: dev128265
  action-gh-release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@master
      - uses: softprops/action-gh-release@master
    
