# This is a basic workflow to help you get started with Actions

name: Github workflow prebuilt

# Controls when the action will run. 
on: [push, workflow_dispatch]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: docker prebuilt
        run: docker --version

      # Runs a set of commands using the runners shell
      - name: mysql prebuilt
        run: mysql -V
