# This is a basic workflow to help you get started with Actions

name: prebuilt in Github workflow environment

# Controls when the action will run. 
on: [push, workflow_dispatch]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  viewPrebuiltVersion:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      # https://github.com/actions/virtual-environments/issues/17#issuecomment-730816023
      - uses: docker-practice/actions-setup-docker@master
        if: ${{ matrix.os == 'macos-latest' }}
      - name: docker prebuilt
        run: docker --version
      - name: mysql prebuilt
        run: mysql -V
