name: StaleProcess

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 0 * * 0' # https://crontab.guru/#0_0_*_*_0

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Close Stale Issues
      uses: actions/stale@v3.0.8
      with:
        # Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.
        repo-token: $(secrets.GITHUB_TOKEN)
        # The message to post on the issue when tagging it. If none provided, will not mark issues stale.
        stale-issue-message: Marked as stale issue, closed.
        # The message to post on the pr when tagging it. If none provided, will not mark pull requests stale.
        stale-pr-message: Marked as stale PR, closed.
        
        # The number of days old an issue can be before marking it stale.
        days-before-stale: 60
        # The number of days to wait to close an issue or pull request after it being marked stale. Set to -1 to never close stale issues.
        days-before-close: 7
        # The label to apply when an issue is stale.
        stale-issue-label: Stale
                
        # The label to apply when a pull request is stale.
        stale-pr-label: Stale
                
        # The maximum number of operations per run, used to control rate limiting.
        operations-per-run: 1
        # Remove stale labels from issues when they are updated or commented on.
        remove-stale-when-updated: true
        
        
