name: StaleProcess

# Controls when the action will run. 
on:
  push:
  schedule:
    - cron: '0 0 * * 0' # https://crontab.guru/#0_0_*_*_0

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - uses: actions/stale@v3
      with:
        # Token for the repository to grant access to this stale bot action
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # The message to post on the issue when tagging it. If none provided, will not mark issues stale.
        stale-issue-message: Marked as stale issue. Will be closed later if no activity for a while. 
        # The message to post on the pr when tagging it. If none provided, will not mark pull requests stale.
        stale-pr-message: Marked as stale PR. Will be closed later if no activity for a while.
        
        # The labels to apply when an issue is exempt from being marked stale. Separate multiple labels with commas (eg. "label1,label2")
        exempt-issue-labels: ''
        
        # The labels to apply when a pull request is exempt from being marked stale. Separate multiple labels with commas (eg. "label1,label2")
        exempt-pr-labels: ''
        
        # The number of days old an issue can be before marking it stale. Set to -1 to never mark issues or pull requests as stale automatically.
        days-before-stale: 60
        # The number of days to wait to close an issue or pull request after it being marked stale. Set to -1 to never close stale issues.
        days-before-close: 7
                
        # The maximum number of operations per run, used to control rate limiting. default is 30
        operations-per-run: 1
        # Run the processor in debug mode without actually performing any operations on live issues.
        debug-only: true
    
        
        
