name: prebuilt in Github workflow environment

# Controls when the action will run. 
on: [push, workflow_dispatch]

jobs:

  viewPrebuiltVersion:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      # https://github.com/actions/virtual-environments/issues/17#issuecomment-730816023
      - uses: docker-practice/actions-setup-docker@master
        if: ${{ matrix.os == 'macos-latest' }}
      - name: docker pre-built
        run: docker --version
      - name: mysql prebuilt
        run: mysql -V
        if: ${{ matrix.os != 'macos-latest' }}
      - name: java pre-built
        run: java -version
        
      - name: node pre-built
        run: node --version
      - name: go pre-built
        run: go version
