name: pre-install software in GHA runner

# Controls when the action will run. 
on: [push, workflow_dispatch]

jobs:

  viewPrebuiltVersion:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      LAYER: Job
    steps:
      - run: echo $LAYER
      - uses: actions/checkout@main
      - uses: docker-practice/actions-setup-docker@master
        if: ${{ matrix.os == 'macos-latest' }}
      - name: docker pre-install
        run: docker --version
      - name: mysql pre-install
        run: mysql -V
        if: ${{ matrix.os != 'macos-latest' }}
      - name: java pre-install
        run: java -version
      - name: python pre-install
        run: python --version
      - name: node pre-built
        run: node --version
      - name: go pre-built
        run: go version
      - uses: actions/setup-go@v2
      - name: after setup Golang
        run: go version
