name: pre-install software in GHA runner

on: 
  push:
env:
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}

jobs:
  view-windows:
    runs-on: windows-latest
    steps:
      - name: default environments
        run: 'Get-ChildItem Env:'
        shell: powershell
   
  view-contexts: # https://docs.github.com/en/actions/learn-github-actions/contexts#example-printing-context-information-to-the-log
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: default environments in https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
        run: echo "CI=${CI};GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}; ${GITHUB_ACTOR}~=${GITHUB_REPOSITORY_OWNER}; GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
      - name: self-defined environments
        run: echo "GITHUB_REPOSITORY_NAME=${GITHUB_REPOSITORY_NAME}"
  
  view-prebuilt-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - name: docker pre-install
        run: docker --version
        if: ${{ matrix.os != 'macos-latest' }}
      - name: mysql pre-install
        run: mysql -V
        if: ${{ matrix.os != 'macos-latest' }}
      - name: java pre-install
        run: java -version
      - name: Rust (cargo) pre-install
        run: cargo --version
      - name: python pre-install
        run: python --version
      - name: python location
        run: which python
        if: ${{ matrix.os != 'macos-latest' }}
      - name: node pre-built
        run: node --version
      - name: go pre-built
        run: go version
        if: ${{ matrix.os != 'macos-latest' }}
      - run: echo $(go env GOOS)
        shell: bash
      - uses: actions/setup-go@main
        with:
          go-version: 'stable'
        # When no go versions are set in workflow file, the default version in GitHub hosted runner is used.
      - name: after setup Golang
        run: go version

