on:
  push:
    tags:
      - "v*.*.*"
jobs:
  
  build-and-release-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.event.push.ref }}
      - name: Release
        if: startsWith(github.event.push.ref, 'refs/tags/')
        uses: softprops/action-gh-release@master
        
